/*--------------------------------------------------------------------------
* linq.js - LINQ for JavaScript
* ver 2.2.0.2 (Jan. 21th, 2011)
* created and maintained by neuecc <ils@neue.cc>
* licensed under Microsoft Public License(Ms-PL)
* http://neue.cc/
* http://linqjs.codeplex.com/
*--------------------------------------------------------------------------*/
Enumerable=function(){var r,u,s,t,i,n,w,e=function(a){this.GetEnumerator=a};e.Choice=function(){var a=arguments[0]instanceof Array?arguments[0]:arguments;return new e(function(){return new h(i,function(){return this.Yield(a[Math.floor(Math.random()*a.length)])},i)})};e.Cycle=function(){var a=arguments[0]instanceof Array?arguments[0]:arguments;return new e(function(){var b=0;return new h(i,function(){b>=a.length&&(b=0);return this.Yield(a[b++])},i)})};e.Empty=function(){return new e(function(){return new h(i,
    function(){return!1},i)})};e.From=function(a){if(null==a)return e.Empty();if(a instanceof e)return a;if(typeof a==r||typeof a==u)return e.Repeat(a,1);if(typeof a==s)return new e(function(){var b=0;return new h(i,function(){return b<a.length?this.Yield(a.charAt(b++)):!1},i)});if(typeof a!=t){if(typeof a.length==r)return new j(a);if(!(a instanceof Object)&&f.IsIEnumerable(a))return new e(function(){var b=!0,c;return new h(function(){c=new Enumerator(a)},function(){b?b=!1:c.moveNext();return c.atEnd()?
    !1:this.Yield(c.item())},i)})}return new e(function(){var b=[],c=0;return new h(function(){for(var c in a)a[c]instanceof Function||b.push({Key:c,Value:a[c]})},function(){return c<b.length?this.Yield(b[c++]):!1},i)})};e.Return=function(a){return e.Repeat(a,1)};e.Matches=function(a,b,c){null==c&&(c="");b instanceof RegExp&&(c+=b.ignoreCase?"i":"",c+=b.multiline?"m":"",b=b.source);-1===c.indexOf("g")&&(c+="g");return new e(function(){var d;return new h(function(){d=RegExp(b,c)},function(){var b=d.exec(a);
    return b?this.Yield(b):false},i)})};e.Range=function(a,b,c){null==c&&(c=1);return e.ToInfinity(a,c).Take(b)};e.RangeDown=function(a,b,c){null==c&&(c=1);return e.ToNegativeInfinity(a,c).Take(b)};e.RangeTo=function(a,b,c){null==c&&(c=1);return a<b?e.ToInfinity(a,c).TakeWhile(function(a){return a<=b}):e.ToNegativeInfinity(a,c).TakeWhile(function(a){return a>=b})};e.Repeat=function(a,b){return null!=b?e.Repeat(a).Take(b):new e(function(){return new h(i,function(){return this.Yield(a)},i)})};e.RepeatWithFinalize=
    function(a,b){a=f.CreateLambda(a);b=f.CreateLambda(b);return new e(function(){var c;return new h(function(){c=a()},function(){return this.Yield(c)},function(){null!=c&&(b(c),c=null)})})};e.Generate=function(a,b){if(null!=b)return e.Generate(a).Take(b);a=f.CreateLambda(a);return new e(function(){return new h(i,function(){return this.Yield(a())},i)})};e.ToInfinity=function(a,b){null==a&&(a=0);null==b&&(b=1);return new e(function(){var c;return new h(function(){c=a-b},function(){return this.Yield(c+=
    b)},i)})};e.ToNegativeInfinity=function(a,b){null==a&&(a=0);null==b&&(b=1);return new e(function(){var c;return new h(function(){c=a+b},function(){return this.Yield(c-=b)},i)})};e.Unfold=function(a,b){b=f.CreateLambda(b);return new e(function(){var c=!0,d;return new h(i,function(){if(c)return c=!1,d=a,this.Yield(d);d=b(d);return this.Yield(d)},i)})};e.prototype={CascadeBreadthFirst:function(a,b){var c=this,a=f.CreateLambda(a),b=f.CreateLambda(b);return new e(function(){var d,g=0,k=[];return new h(function(){d=
    c.GetEnumerator()},function(){for(;;){if(d.MoveNext())return k.push(d.Current()),this.Yield(b(d.Current(),g));var c=e.From(k).SelectMany(function(b){return a(b)});if(c.Any())g++,k=[],f.Dispose(d),d=c.GetEnumerator();else return!1}},function(){f.Dispose(d)})})},CascadeDepthFirst:function(a,b){var c=this,a=f.CreateLambda(a),b=f.CreateLambda(b);return new e(function(){var d=[],g;return new h(function(){g=c.GetEnumerator()},function(){for(;;){if(g.MoveNext()){var c=b(g.Current(),d.length);d.push(g);g=
    e.From(a(g.Current())).GetEnumerator();return this.Yield(c)}if(0>=d.length)return!1;f.Dispose(g);g=d.pop()}},function(){try{f.Dispose(g)}finally{e.From(d).ForEach(function(a){a.Dispose()})}})})},Flatten:function(){var a=this;return new e(function(){var b,c=null;return new h(function(){b=a.GetEnumerator()},function(){for(;;){if(null!=c){if(c.MoveNext())return this.Yield(c.Current());c=null}if(b.MoveNext())if(b.Current()instanceof Array){f.Dispose(c);c=e.From(b.Current()).SelectMany(n).Flatten().GetEnumerator();
    continue}else return this.Yield(b.Current());return!1}},function(){try{f.Dispose(b)}finally{f.Dispose(c)}})})},Pairwise:function(a){var b=this,a=f.CreateLambda(a);return new e(function(){var c;return new h(function(){c=b.GetEnumerator();c.MoveNext()},function(){var b=c.Current();return c.MoveNext()?this.Yield(a(b,c.Current())):!1},function(){f.Dispose(c)})})},Scan:function(a,b,c){if(null!=c)return this.Scan(a,b).Select(c);var d;null==b?(b=f.CreateLambda(a),d=!1):(b=f.CreateLambda(b),d=!0);var g=this;
    return new e(function(){var c,e,m=true;return new h(function(){c=g.GetEnumerator()},function(){if(m){m=false;if(d)return this.Yield(e=a);if(c.MoveNext())return this.Yield(e=c.Current())}return c.MoveNext()?this.Yield(e=b(e,c.Current())):false},function(){f.Dispose(c)})})},Select:function(a){var b=this,a=f.CreateLambda(a);return new e(function(){var c,d=0;return new h(function(){c=b.GetEnumerator()},function(){return c.MoveNext()?this.Yield(a(c.Current(),d++)):!1},function(){f.Dispose(c)})})},SelectMany:function(a,b){var c=this,a=f.CreateLambda(a);null==b&&(b=function(a,b){return b});b=f.CreateLambda(b);return new e(function(){var d,g=void 0,k=0;return new h(function(){d=c.GetEnumerator()},function(){if(void 0===g&&!d.MoveNext())return!1;do{if(null==g){var c=a(d.Current(),k++);g=e.From(c).GetEnumerator()}if(g.MoveNext())return this.Yield(b(d.Current(),g.Current()));f.Dispose(g);g=null}while(d.MoveNext());return!1},function(){try{f.Dispose(d)}finally{f.Dispose(g)}})})},Where:function(a){var a=f.CreateLambda(a),
    b=this;return new e(function(){var c,d=0;return new h(function(){c=b.GetEnumerator()},function(){for(;c.MoveNext();)if(a(c.Current(),d++))return this.Yield(c.Current());return!1},function(){f.Dispose(c)})})},OfType:function(a){var b;switch(a){case Number:b=r;break;case String:b=s;break;case Boolean:b=u;break;case Function:b=t;break;default:b=null}return null===b?this.Where(function(b){return b instanceof a}):this.Where(function(a){return typeof a===b})},Zip:function(a,b){var b=f.CreateLambda(b),c=
    this;return new e(function(){var d,g,k=0;return new h(function(){d=c.GetEnumerator();g=e.From(a).GetEnumerator()},function(){return d.MoveNext()&&g.MoveNext()?this.Yield(b(d.Current(),g.Current(),k++)):!1},function(){try{f.Dispose(d)}finally{f.Dispose(g)}})})},Join:function(a,b,c,d,g){var b=f.CreateLambda(b),c=f.CreateLambda(c),d=f.CreateLambda(d),g=f.CreateLambda(g),k=this;return new e(function(){var l,m,i=null,j=0;return new h(function(){l=k.GetEnumerator();m=e.From(a).ToLookup(c,n,g)},function(){for(;;){if(null!=
    i){var a=i[j++];if(void 0!==a)return this.Yield(d(l.Current(),a));j=0}if(l.MoveNext())a=b(l.Current()),i=m.Get(a).ToArray();else return!1}},function(){f.Dispose(l)})})},GroupJoin:function(a,b,c,d,g){var b=f.CreateLambda(b),c=f.CreateLambda(c),d=f.CreateLambda(d),g=f.CreateLambda(g),k=this;return new e(function(){var l=k.GetEnumerator(),m=null;return new h(function(){l=k.GetEnumerator();m=e.From(a).ToLookup(c,n,g)},function(){if(l.MoveNext()){var a=m.Get(b(l.Current()));return this.Yield(d(l.Current(),
    a))}return!1},function(){f.Dispose(l)})})},All:function(a){var a=f.CreateLambda(a),b=!0;this.ForEach(function(c){if(!a(c))return b=!1});return b},Any:function(a){var a=f.CreateLambda(a),b=this.GetEnumerator();try{if(0==arguments.length)return b.MoveNext();for(;b.MoveNext();)if(a(b.Current()))return!0;return!1}finally{f.Dispose(b)}},Concat:function(a){var b=this;return new e(function(){var c,d;return new h(function(){c=b.GetEnumerator()},function(){if(null==d){if(c.MoveNext())return this.Yield(c.Current());
    d=e.From(a).GetEnumerator()}return d.MoveNext()?this.Yield(d.Current()):!1},function(){try{f.Dispose(c)}finally{f.Dispose(d)}})})},Insert:function(a,b){var c=this;return new e(function(){var d,g,k=0,l=!1;return new h(function(){d=c.GetEnumerator();g=e.From(b).GetEnumerator()},function(){return k==a&&g.MoveNext()?(l=!0,this.Yield(g.Current())):d.MoveNext()?(k++,this.Yield(d.Current())):!l&&g.MoveNext()?this.Yield(g.Current()):!1},function(){try{f.Dispose(d)}finally{f.Dispose(g)}})})},Alternate:function(a){a=
    e.Return(a);return this.SelectMany(function(b){return e.Return(b).Concat(a)}).TakeExceptLast()},Contains:function(a,b){var b=f.CreateLambda(b),c=this.GetEnumerator();try{for(;c.MoveNext();)if(b(c.Current())===a)return!0;return!1}finally{f.Dispose(c)}},DefaultIfEmpty:function(a){var b=this;return new e(function(){var c,d=!0;return new h(function(){c=b.GetEnumerator()},function(){return c.MoveNext()?(d=!1,this.Yield(c.Current())):d?(d=!1,this.Yield(a)):!1},function(){f.Dispose(c)})})},Distinct:function(a){return this.Except(e.Empty(),
    a)},Except:function(a,b){var b=f.CreateLambda(b),c=this;return new e(function(){var d,g;return new h(function(){d=c.GetEnumerator();g=new p(b);e.From(a).ForEach(function(a){g.Add(a)})},function(){for(;d.MoveNext();){var a=d.Current();if(!g.Contains(a))return g.Add(a),this.Yield(a)}return!1},function(){f.Dispose(d)})})},Intersect:function(a,b){var b=f.CreateLambda(b),c=this;return new e(function(){var d,g,k;return new h(function(){d=c.GetEnumerator();g=new p(b);e.From(a).ForEach(function(a){g.Add(a)});
    k=new p(b)},function(){for(;d.MoveNext();){var a=d.Current();if(!k.Contains(a)&&g.Contains(a))return k.Add(a),this.Yield(a)}return!1},function(){f.Dispose(d)})})},SequenceEqual:function(a,b){var b=f.CreateLambda(b),c=this.GetEnumerator();try{var d=e.From(a).GetEnumerator();try{for(;c.MoveNext();)if(!d.MoveNext()||b(c.Current())!==b(d.Current()))return!1;return d.MoveNext()?!1:!0}finally{f.Dispose(d)}}finally{f.Dispose(c)}},Union:function(a,b){var b=f.CreateLambda(b),c=this;return new e(function(){var d,
    g,k;return new h(function(){d=c.GetEnumerator();k=new p(b)},function(){var b;if(void 0===g){for(;d.MoveNext();)if(b=d.Current(),!k.Contains(b))return k.Add(b),this.Yield(b);g=e.From(a).GetEnumerator()}for(;g.MoveNext();)if(b=g.Current(),!k.Contains(b))return k.Add(b),this.Yield(b);return!1},function(){try{f.Dispose(d)}finally{f.Dispose(g)}})})},OrderBy:function(a){return new o(this,a,!1)},OrderByDescending:function(a){return new o(this,a,!0)},Reverse:function(){var a=this;return new e(function(){var b,
    c;return new h(function(){b=a.ToArray();c=b.length},function(){return 0<c?this.Yield(b[--c]):!1},i)})},Shuffle:function(){var a=this;return new e(function(){var b;return new h(function(){b=a.ToArray()},function(){if(0<b.length){var a=Math.floor(Math.random()*b.length);return this.Yield(b.splice(a,1)[0])}return!1},i)})},GroupBy:function(a,b,c,d){var g=this,a=f.CreateLambda(a),b=f.CreateLambda(b);null!=c&&(c=f.CreateLambda(c));d=f.CreateLambda(d);return new e(function(){var e;return new h(function(){e=
    g.ToLookup(a,b,d).ToEnumerable().GetEnumerator()},function(){for(;e.MoveNext();)return null==c?this.Yield(e.Current()):this.Yield(c(e.Current().Key(),e.Current()));return!1},function(){f.Dispose(e)})})},PartitionBy:function(a,b,c,d){var g=this,a=f.CreateLambda(a),b=f.CreateLambda(b),d=f.CreateLambda(d),k;null==c?(k=!1,c=function(a,b){return new v(a,b)}):(k=!0,c=f.CreateLambda(c));return new e(function(){var l,m,i,j=[];return new h(function(){l=g.GetEnumerator();if(l.MoveNext()){m=a(l.Current());i=
    d(m);j.push(b(l.Current()))}},function(){for(var g;(g=l.MoveNext())==true;)if(i===d(a(l.Current())))j.push(b(l.Current()));else break;if(j.length>0){var f=k?c(m,e.From(j)):c(m,j);if(g){m=a(l.Current());i=d(m);j=[b(l.Current())]}else j=[];return this.Yield(f)}return false},function(){f.Dispose(l)})})},BufferWithCount:function(a){var b=this;return new e(function(){var c;return new h(function(){c=b.GetEnumerator()},function(){for(var b=[],g=0;c.MoveNext();)if(b.push(c.Current()),++g>=a)return this.Yield(b);
    return 0<b.length?this.Yield(b):!1},function(){f.Dispose(c)})})},Aggregate:function(a,b,c){return this.Scan(a,b,c).Last()},Average:function(a){var a=f.CreateLambda(a),b=0,c=0;this.ForEach(function(d){b+=a(d);++c});return b/c},Count:function(a){var a=null==a?w:f.CreateLambda(a),b=0;this.ForEach(function(c,d){a(c,d)&&++b});return b},Max:function(a){null==a&&(a=n);return this.Select(a).Aggregate(function(a,c){return a>c?a:c})},Min:function(a){null==a&&(a=n);return this.Select(a).Aggregate(function(a,c){return a<c?a:c})},MaxBy:function(a){a=f.CreateLambda(a);return this.Aggregate(function(b,c){return a(b)>a(c)?b:c})},MinBy:function(a){a=f.CreateLambda(a);return this.Aggregate(function(b,c){return a(b)<a(c)?b:c})},Sum:function(a){null==a&&(a=n);return this.Select(a).Aggregate(0,function(a,c){return a+c})},ElementAt:function(a){var b,c=!1;this.ForEach(function(d,g){if(g==a)return b=d,c=!0,!1});if(!c)throw Error("index is less than 0 or greater than or equal to the number of elements in source.");
    return b},ElementAtOrDefault:function(a,b){var c,d=!1;this.ForEach(function(b,e){if(e==a)return c=b,d=!0,!1});return!d?b:c},First:function(a){if(null!=a)return this.Where(a).First();var b,c=!1;this.ForEach(function(a){b=a;c=!0;return!1});if(!c)throw Error("First:No element satisfies the condition.");return b},FirstOrDefault:function(a,b){if(null!=b)return this.Where(b).FirstOrDefault(a);var c,d=!1;this.ForEach(function(a){c=a;d=!0;return!1});return!d?a:c},Last:function(a){if(null!=a)return this.Where(a).Last();
    var b,c=!1;this.ForEach(function(a){c=!0;b=a});if(!c)throw Error("Last:No element satisfies the condition.");return b},LastOrDefault:function(a,b){if(null!=b)return this.Where(b).LastOrDefault(a);var c,d=!1;this.ForEach(function(a){d=!0;c=a});return!d?a:c},Single:function(a){if(null!=a)return this.Where(a).Single();var b,c=!1;this.ForEach(function(a){if(c)throw Error("Single:sequence contains more than one element.");c=!0;b=a});if(!c)throw Error("Single:No element satisfies the condition.");return b},
    SingleOrDefault:function(a,b){if(null!=b)return this.Where(b).SingleOrDefault(a);var c,d=!1;this.ForEach(function(a){if(d)throw Error("Single:sequence contains more than one element.");d=!0;c=a});return!d?a:c},Skip:function(a){var b=this;return new e(function(){var c,d=0;return new h(function(){for(c=b.GetEnumerator();d++<a&&c.MoveNext(););},function(){return c.MoveNext()?this.Yield(c.Current()):!1},function(){f.Dispose(c)})})},SkipWhile:function(a){var a=f.CreateLambda(a),b=this;return new e(function(){var c,
        d=0,g=!1;return new h(function(){c=b.GetEnumerator()},function(){for(;!g;)if(c.MoveNext()){if(!a(c.Current(),d++))return g=!0,this.Yield(c.Current())}else return!1;return c.MoveNext()?this.Yield(c.Current()):!1},function(){f.Dispose(c)})})},Take:function(a){var b=this;return new e(function(){var c,d=0;return new h(function(){c=b.GetEnumerator()},function(){return d++<a&&c.MoveNext()?this.Yield(c.Current()):!1},function(){f.Dispose(c)})})},TakeWhile:function(a){var a=f.CreateLambda(a),b=this;return new e(function(){var c,
        d=0;return new h(function(){c=b.GetEnumerator()},function(){return c.MoveNext()&&a(c.Current(),d++)?this.Yield(c.Current()):!1},function(){f.Dispose(c)})})},TakeExceptLast:function(a){null==a&&(a=1);var b=this;return new e(function(){if(0>=a)return b.GetEnumerator();var c,d=[];return new h(function(){c=b.GetEnumerator()},function(){for(;c.MoveNext();){if(d.length==a)return d.push(c.Current()),this.Yield(d.shift());d.push(c.Current())}return!1},function(){f.Dispose(c)})})},TakeFromLast:function(a){if(0>=
        a||null==a)return e.Empty();var b=this;return new e(function(){var c,d,g=[];return new h(function(){c=b.GetEnumerator()},function(){for(;c.MoveNext();)g.length==a&&g.shift(),g.push(c.Current());null==d&&(d=e.From(g).GetEnumerator());return d.MoveNext()?this.Yield(d.Current()):!1},function(){f.Dispose(d)})})},IndexOf:function(a){var b=null;this.ForEach(function(c,d){if(c===a)return b=d,!0});return null!==b?b:-1},LastIndexOf:function(a){var b=-1;this.ForEach(function(c,d){c===a&&(b=d)});return b},ToArray:function(){var a=
        [];this.ForEach(function(b){a.push(b)});return a},ToLookup:function(a,b,c){var a=f.CreateLambda(a),b=f.CreateLambda(b),c=f.CreateLambda(c),d=new p(c);this.ForEach(function(c){var e=a(c),c=b(c),f=d.Get(e);void 0!==f?f.push(c):d.Add(e,[c])});return new x(d)},ToObject:function(a,b){var a=f.CreateLambda(a),b=f.CreateLambda(b),c={};this.ForEach(function(d){c[a(d)]=b(d)});return c},ToDictionary:function(a,b,c){var a=f.CreateLambda(a),b=f.CreateLambda(b),c=f.CreateLambda(c),d=new p(c);this.ForEach(function(c){d.Add(a(c),
        b(c))});return d},ToJSON:function(a,b){return JSON.stringify(this.ToArray(),a,b)},ToString:function(a,b){null==a&&(a="");null==b&&(b=n);return this.Select(b).ToArray().join(a)},Do:function(a){var b=this,a=f.CreateLambda(a);return new e(function(){var c,d=0;return new h(function(){c=b.GetEnumerator()},function(){return c.MoveNext()?(a(c.Current(),d++),this.Yield(c.Current())):!1},function(){f.Dispose(c)})})},ForEach:function(a){var a=f.CreateLambda(a),b=0,c=this.GetEnumerator();try{for(;c.MoveNext()&&!1!==a(c.Current(),b++););}finally{f.Dispose(c)}},Write:function(a,b){null==a&&(a="");var b=f.CreateLambda(b),c=!0;this.ForEach(function(d){c?c=!1:document.write(a);document.write(b(d))})},WriteLine:function(a){a=f.CreateLambda(a);this.ForEach(function(b){document.write(a(b));document.write("<br />")})},Force:function(){var a=this.GetEnumerator();try{for(;a.MoveNext(););}finally{f.Dispose(a)}},Let:function(a){var a=f.CreateLambda(a),b=this;return new e(function(){var c;return new h(function(){c=e.From(a(b)).GetEnumerator()},
        function(){return c.MoveNext()?this.Yield(c.Current()):!1},function(){f.Dispose(c)})})},Share:function(){var a=this,b;return new e(function(){return new h(function(){null==b&&(b=a.GetEnumerator())},function(){return b.MoveNext()?this.Yield(b.Current()):!1},i)})},MemoizeAll:function(){var a=this,b,c;return new e(function(){var d=-1;return new h(function(){null==c&&(c=a.GetEnumerator(),b=[])},function(){d++;return b.length<=d?c.MoveNext()?this.Yield(b[d]=c.Current()):!1:this.Yield(b[d])},i)})},Catch:function(a){var a=
        f.CreateLambda(a),b=this;return new e(function(){var c;return new h(function(){c=b.GetEnumerator()},function(){try{return c.MoveNext()?this.Yield(c.Current()):!1}catch(b){return a(b),!1}},function(){f.Dispose(c)})})},Finally:function(a){var a=f.CreateLambda(a),b=this;return new e(function(){var c;return new h(function(){c=b.GetEnumerator()},function(){return c.MoveNext()?this.Yield(c.Current()):!1},function(){try{f.Dispose(c)}finally{a()}})})},Trace:function(a,b){null==a&&(a="Trace");b=f.CreateLambda(b);
        return this.Do(function(c){console.log(a,":",b(c))})}};n=function(a){return a};w=function(){return!0};i=function(){};u="boolean";r="number";s="string";t="function";var f={CreateLambda:function(a){if(null==a)return n;if(typeof a==s){if(""==a)return n;if(-1==a.indexOf("=>"))return new Function("$,$$,$$$,$$$$","return "+a);a=a.match(/^[(\s]*([^()]*?)[)\s]*=>(.*)/);return new Function(a[1],"return "+a[2])}return a},IsIEnumerable:function(a){if("undefined"!=typeof Enumerator)try{return new Enumerator(a),
    !0}catch(b){}return!1},Compare:function(a,b){return a===b?0:a>b?1:-1},Dispose:function(a){null!=a&&a.Dispose()}},h=function(a,b,c){var d=new y,g=0;this.Current=d.Current;this.MoveNext=function(){try{switch(g){case 0:g=1,a();case 1:if(b.apply(d))return!0;this.Dispose();return!1;case 2:return!1}}catch(c){throw this.Dispose(),c;}};this.Dispose=function(){if(1==g)try{c()}finally{g=2}}},y=function(){var a=null;this.Current=function(){return a};this.Yield=function(b){a=b;return!0}},o=function(a,b,c,d){this.source=
    a;this.keySelector=f.CreateLambda(b);this.descending=c;this.parent=d};o.prototype=new e;o.prototype.CreateOrderedEnumerable=function(a,b){return new o(this.source,a,b,this)};o.prototype.ThenBy=function(a){return this.CreateOrderedEnumerable(a,!1)};o.prototype.ThenByDescending=function(a){return this.CreateOrderedEnumerable(a,!0)};o.prototype.GetEnumerator=function(){var a=this,b,c,d=0;return new h(function(){b=[];c=[];a.source.ForEach(function(a,d){b.push(a);c.push(d)});var d=q.Create(a,null);d.GenerateKeys(b);
    c.sort(function(a,b){return d.Compare(a,b)})},function(){return d<c.length?this.Yield(b[c[d++]]):!1},i)};var q=function(a,b,c){this.keySelector=a;this.descending=b;this.child=c;this.keys=null};q.Create=function(a,b){var c=new q(a.keySelector,a.descending,b);return null!=a.parent?q.Create(a.parent,c):c};q.prototype.GenerateKeys=function(a){for(var b=a.length,c=this.keySelector,d=Array(b),g=0;g<b;g++)d[g]=c(a[g]);this.keys=d;null!=this.child&&this.child.GenerateKeys(a)};q.prototype.Compare=function(a,b){var c=f.Compare(this.keys[a],this.keys[b]);if(0==c){if(null!=this.child)return this.child.Compare(a,b);c=f.Compare(a,b)}return this.descending?-c:c};var j=function(a){this.source=a};j.prototype=new e;j.prototype.Any=function(a){return null==a?0<this.source.length:e.prototype.Any.apply(this,arguments)};j.prototype.Count=function(a){return null==a?this.source.length:e.prototype.Count.apply(this,arguments)};j.prototype.ElementAt=function(a){return 0<=a&&a<this.source.length?this.source[a]:e.prototype.ElementAt.apply(this,
    arguments)};j.prototype.ElementAtOrDefault=function(a,b){return 0<=a&&a<this.source.length?this.source[a]:b};j.prototype.First=function(a){return null==a&&0<this.source.length?this.source[0]:e.prototype.First.apply(this,arguments)};j.prototype.FirstOrDefault=function(a,b){return null!=b?e.prototype.FirstOrDefault.apply(this,arguments):0<this.source.length?this.source[0]:a};j.prototype.Last=function(a){return null==a&&0<this.source.length?this.source[this.source.length-1]:e.prototype.Last.apply(this,
    arguments)};j.prototype.LastOrDefault=function(a,b){return null!=b?e.prototype.LastOrDefault.apply(this,arguments):0<this.source.length?this.source[this.source.length-1]:a};j.prototype.Skip=function(a){var b=this.source;return new e(function(){var c;return new h(function(){c=0>a?0:a},function(){return c<b.length?this.Yield(b[c++]):!1},i)})};j.prototype.TakeExceptLast=function(a){null==a&&(a=1);return this.Take(this.source.length-a)};j.prototype.TakeFromLast=function(a){return this.Skip(this.source.length-
    a)};j.prototype.Reverse=function(){var a=this.source;return new e(function(){var b;return new h(function(){b=a.length},function(){return 0<b?this.Yield(a[--b]):!1},i)})};j.prototype.SequenceEqual=function(a,b){return(a instanceof j||a instanceof Array)&&null==b&&e.From(a).Count()!=this.Count()?!1:e.prototype.SequenceEqual.apply(this,arguments)};j.prototype.ToString=function(a,b){if(null!=b||!(this.source instanceof Array))return e.prototype.ToString.apply(this,arguments);null==a&&(a="");return this.source.join(a)};
    j.prototype.GetEnumerator=function(){var a=this.source,b=0;return new h(i,function(){return b<a.length?this.Yield(a[b++]):!1},i)};var p=function(){var a=function(a){return null===a?"null":void 0===a?"undefined":typeof a.toString===t?a.toString():Object.prototype.toString.call(a)},b=function(a,b){this.Key=a;this.Value=b;this.Next=this.Prev=null},c=function(){this.Last=this.First=null};c.prototype={AddLast:function(a){null!=this.Last?(this.Last.Next=a,a.Prev=this.Last,this.Last=a):this.First=this.Last=
            a},Replace:function(a,b){null!=a.Prev?(a.Prev.Next=b,b.Prev=a.Prev):this.First=b;null!=a.Next?(a.Next.Prev=b,b.Next=a.Next):this.Last=b},Remove:function(a){null!=a.Prev?a.Prev.Next=a.Next:this.First=a.Next;null!=a.Next?a.Next.Prev=a.Prev:this.Last=a.Prev}};var d=function(a){this.count=0;this.entryList=new c;this.buckets={};this.compareSelector=null==a?n:a};d.prototype={Add:function(c,d){var e=this.compareSelector(c),f=a(e),h=new b(c,d);if(Object.prototype.hasOwnProperty.call(this.buckets,f)){for(var f=
            this.buckets[f],i=0;i<f.length;i++)if(this.compareSelector(f[i].Key)===e){this.entryList.Replace(f[i],h);f[i]=h;return}f.push(h)}else this.buckets[f]=[h];this.count++;this.entryList.AddLast(h)},Get:function(b){var b=this.compareSelector(b),c=a(b);if(Object.prototype.hasOwnProperty.call(this.buckets,c))for(var c=this.buckets[c],d=0;d<c.length;d++){var e=c[d];if(this.compareSelector(e.Key)===b)return e.Value}},Set:function(c,d){var e=this.compareSelector(c),f=a(e);if(Object.prototype.hasOwnProperty.call(this.buckets,
            f))for(var f=this.buckets[f],h=0;h<f.length;h++)if(this.compareSelector(f[h].Key)===e)return e=new b(c,d),this.entryList.Replace(f[h],e),f[h]=e,!0;return!1},Contains:function(b){var b=this.compareSelector(b),c=a(b);if(!Object.prototype.hasOwnProperty.call(this.buckets,c))return!1;for(var c=this.buckets[c],d=0;d<c.length;d++)if(this.compareSelector(c[d].Key)===b)return!0;return!1},Clear:function(){this.count=0;this.buckets={};this.entryList=new c},Remove:function(b){var b=this.compareSelector(b),c=
            a(b);if(Object.prototype.hasOwnProperty.call(this.buckets,c))for(var d=this.buckets[c],e=0;e<d.length;e++)if(this.compareSelector(d[e].Key)===b){this.entryList.Remove(d[e]);d.splice(e,1);0==d.length&&delete this.buckets[c];this.count--;break}},Count:function(){return this.count},ToEnumerable:function(){var a=this;return new e(function(){var b;return new h(function(){b=a.entryList.First},function(){if(null!=b){var a={Key:b.Key,Value:b.Value};b=b.Next;return this.Yield(a)}return!1},i)})}};return d}(),
        x=function(a){this.Count=function(){return a.Count()};this.Get=function(b){return e.From(a.Get(b))};this.Contains=function(b){return a.Contains(b)};this.ToEnumerable=function(){return a.ToEnumerable().Select(function(a){return new v(a.Key,a.Value)})}},v=function(a,b){this.Key=function(){return a};this.source=b};v.prototype=new j;return e}();